"""Initial migration

Revision ID: db45d7e7309f
Revises: 
Create Date: 2025-04-03 14:28:51.359997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db45d7e7309f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camps',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('food_capacity', sa.Integer(), nullable=True),
    sa.Column('water_capacity', sa.Integer(), nullable=True),
    sa.Column('essentials_capacity', sa.Integer(), nullable=True),
    sa.Column('clothes_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('camp_head_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_lat', sa.Float(), nullable=False),
    sa.Column('coordinates_lng', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('people_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camp_head_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('feedback',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('sensor',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_reading', sa.DateTime(), nullable=True),
    sa.Column('moisture_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('associated_camp_id', sa.Integer(), nullable=True),
    sa.Column('associated_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['associated_camp_id'], ['camps.cid'], ),
    sa.ForeignKeyConstraint(['associated_warehouse_id'], ['warehouses.wid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vid'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('volunteer_role',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('warehouses',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('coordinates_lat', sa.Float(), nullable=False),
    sa.Column('coordinates_lng', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('food_capacity', sa.Integer(), nullable=False),
    sa.Column('water_capacity', sa.Integer(), nullable=False),
    sa.Column('essential_capacity', sa.Integer(), nullable=False),
    sa.Column('clothes_capacity', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    op.create_table('camp_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_donation_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('donation_amount',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_donation_amount_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'amount_id')
    )
    op.create_table('recent_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_recent_activity_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_thread_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_user_activity_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_volunteer_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vid')
    )
    op.create_table('reply',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.tid'], name='fk_reply_thread_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name='fk_reply_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('volunteer_history',
    sa.Column('vhid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.cid'], name='fk_volunteer_history_camp_cid', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_role.role_id'], name='fk_volunteer_history_role_role_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vid'], ['volunteer.vid'], name='fk_volunteer_history_volunteer_vid', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vhid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_history')
    op.drop_table('reply')
    op.drop_table('volunteer')
    op.drop_table('user_activity')
    op.drop_table('thread')
    op.drop_table('recent_activities')
    op.drop_table('donation_amount')
    op.drop_table('donation')
    op.drop_table('camp_notifications')
    op.drop_table('warehouses')
    op.drop_table('volunteer_role')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('sensor')
    op.drop_table('feedback')
    op.drop_table('camps')
    # ### end Alembic commands ###
